name: 🔍 Scheduled Change Detection

on:
  schedule:
    # 8 AM Lisbon Time (UTC+1 in winter, UTC+2 in summer)
    - cron: '0 7 * * *'   # Winter
    - cron: '0 6 * * *'   # Summer
    # 4 PM Lisbon Time
    - cron: '0 15 * * *'  # Winter
    - cron: '0 14 * * *'  # Summer
  workflow_dispatch:

env:
  NODE_VERSION: '22'
  TARGET_REPO: 'politrackpt/Open-Data-Retrieval'

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
    - name: 🔧 Checkout Repository
      uses: actions/checkout@v4

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 📦 Install Dependencies
      run: npm ci

    - name: 🎭 Install Playwright Browsers
      run: npx playwright install firefox

    - name: 🔍 Run Change Detection
      run: npm run default
      continue-on-error: true

    - name: 📋 Check if Changes Detected
      id: check-changes
      run: |
        if [ -f "data/change-report.json" ]; then
          if [ -s "data/change-report.json" ] && ! grep -q '^{}$' "data/change-report.json"; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
            echo "📊 Changes detected - triggering Open-Data-Retrieval"
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
            echo "✅ No changes detected - skipping trigger"
          fi
        else
          echo "changes_detected=false" >> $GITHUB_OUTPUT
          echo "❌ No change-report.json file generated"
        fi

    - name: 🚀 Trigger Open-Data-Retrieval
      if: steps.check-changes.outputs.changes_detected == 'true'
      run: |
        ENCODED=$(base64 -w 0 data/change-report.json)
        curl -X POST \
          -H "Authorization: token ${{ secrets.CROSS_REPO_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/politrackpt/Open-Data-Retrieval/dispatches \
          -d @- <<EOF
        {
          "event_type": "ar-changes-detected",
          "client_payload": {
            "changes": "$ENCODED",
            "source_repo": "${{ github.repository }}",
            "source_run_id": "${{ github.run_id }}"
          }
        }
        EOF

    - name: 💾 Commit Updated Hashes
      if: always()
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

        git add data/hashes.json

        if git diff --cached --quiet; then
          echo "🟢 No changes to commit."
        else
          git commit -m "🔄 Update hashes.json after change detection [skip ci]"
          git push origin ${{ github.ref_name }}
        fi

    - name: ✅ Finished
      run: echo "Workflow completed"